apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../storage.k8s.io/v1/
  - ../../base/core/v1/
  - ../../tekton.dev/v1beta1/pipeline/
  - ../../tekton.dev/v1beta1/task/
  - ../../templates/
namespace: okd-team
